#! /usr/bin/env node

import inquirer from "inquirer"
import Choices from "inquirer/lib/objects/choices.js";

async function start(){
//create a variable to store a random number generated by computer btw 0-9
    let secretnumber=Math.floor(Math.random()*10);
 
    //asking the user to guess the secret number
const answer=await inquirer.prompt([{
    type:"string",
    name:"question",
    message:"Guess the secret number from 0-9?"
}])

//showing the user the number they selected and the number generated by comp
console.log(`user's guess=${answer.question}`)
console.log(`system generated number=${secretnumber}`);

//IF user selected the correct number showing him the msg you won else you lose
if (answer.question== secretnumber){
    console.log("You won.");
}

else{
    console.log("you lose.");
    
}

// asking the user if he wants to play again
const question=await inquirer.prompt([{
    type:"list",
    name:"continue",
    message:"would you like to play again?",
    choices:["yes","No"]
}])

// if the user selects yes showing him the questions again
if (question.continue=="yes"){
start()
}
}
start()